version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5175:5175"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=https://pabomqopgvaekbrblcnk.supabase.co
      - VITE_SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYm9tcW9wZ3ZhZWticmJsY25rIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDkxMDYzMSwiZXhwIjoyMDYwNDg2NjMxfQ.DIZ1ykCjhDfx8zT2FUYm-E3snI4YxaZxsdhuvYmAm5I

    restart: unless-stopped 